services:
  - type: web
    name: bcra-proxy-scoring
    runtime: docker # Aqu√≠ le obligamos a usar Docker
    plan: free
    envVars:
      - key: PUPPETEER_EXECUTABLE_PATH
        value: /usr/bin/google-chrome
